#!/usr/bin/env python3
"""composer-modes desktop patcher — transactional, anchored, reversible.

Applies the desktop-side seam (the composer-mode frame + the per-entry queue
freeze) to a Hermes Agent checkout's renderer sources:

    apps/desktop/src/app/chat/composer/*             frame plumbing
    apps/desktop/src/store/composer-queue.ts         sealed entry payload
    apps/desktop/src/app/session/hooks/*             drain + steer hand-back
    apps/desktop/src/app/chat/*                      tile actions + wiring
    apps/desktop/AGENTS.md                           the contract note

The operations live in ``ops.json`` (renderer sources) and ``test-ops.json``
(the contract tests; optional, pick with --set tests) next to this file:
ordered exact search/replace pairs generated by gen_ops.py from a verified
diff. The patcher is all-or-nothing:

  phase A  every anchor must match exactly once (read-only)
  phase B  backup (.bak-<stamp>-<rand>, never overwrites) then write;
           a brand-new file (create op) is written whole, no backup
  phase C  re-verify every target string + token -> else rollback everything

The real syntax gate for TypeScript is the build itself:
build-desktop-seam.ps1 runs ``npm run build`` right after this patch, and a
broken rewrite fails there before anything is swapped.

Exit codes: 0 ok/no-op | 2 anchors missing (nothing written) | 3 failed,
rolled back clean | 4 ROLLBACK INCOMPLETE (files listed) | 5 bad
usage/environment.
"""

from __future__ import annotations

import argparse
import ast
import datetime as _dt
import hashlib
import json
import os
import random
import shutil
import sys
from pathlib import Path

TOKEN = "[composer-modes-desktop-patch]"
HERE = Path(__file__).resolve().parent
SETS = {
    "source": ("ops.json", "composer-modes-desktop-patch-manifest.json"),
    "tests": ("test-ops.json", "composer-modes-desktop-tests-manifest.json"),
}
PROBE = ("apps", "desktop", "src", "app", "chat", "composer", "hooks", "use-composer-queue.ts")


def log(msg: str) -> None:
    print(f"[composer-modes-desktop] {msg}", flush=True)


def find_repo(explicit: str | None) -> Path | None:
    cands: list[Path] = []
    if explicit:
        cands.append(Path(explicit))
    else:
        here = Path.cwd()
        for base in [here, *here.parents]:
            if (base.joinpath(*PROBE)).is_file():
                cands.append(base)
                break
        env = os.environ.get("HERMES_AGENT_DIR")
        if env:
            cands.append(Path(env))
        local = os.environ.get("LOCALAPPDATA")
        if local:
            cands.append(Path(local) / "hermes" / "hermes-agent")
        cands.append(Path.home() / ".hermes" / "hermes-agent")
    for c in cands:
        if (c.joinpath(*PROBE)).is_file():
            return c
    return None


def read_text(p: Path) -> str:
    with p.open(encoding="utf-8", newline="") as fh:
        return fh.read().replace("\r\n", "\n")


def token_line(rel: str) -> str:
    return f"<!-- {TOKEN} -->" if rel.endswith(".md") else f"// {TOKEN}"


def has_token(text: str) -> bool:
    return TOKEN in text


def is_create(ops: list[dict]) -> bool:
    return len(ops) == 1 and bool(ops[0].get("create"))


def is_fully_applied(text: str, ops: list[dict]) -> bool:
    return all((op["new"] in text) if op["new"] else True for op in ops)


def missing_anchors(text: str, ops: list[dict]) -> list[int]:
    return [i for i, op in enumerate(ops) if op["old"] and text.count(op["old"]) != 1]


def backup_path(p: Path) -> Path:
    stamp = _dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    for _ in range(50):
        cand = p.with_name(p.name + f".bak-{stamp}-{random.randint(0x1000, 0xFFFF):x}")
        if not cand.exists():
            return cand
    raise RuntimeError(f"could not allocate a backup name next to {p}")


def apply_ops(text: str, ops: list[dict]) -> str:
    for op in ops:
        if op["old"]:
            text = text.replace(op["old"], op["new"], 1)
        else:
            text = text + ("" if text.endswith("\n") else "\n") + op["new"]
    return text


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _finish(report: dict, args: argparse.Namespace) -> None:
    if args.json:
        report["token"] = TOKEN
        print(json.dumps(report, indent=2, ensure_ascii=False))


def main() -> int:
    ap = argparse.ArgumentParser(description="composer-modes desktop patcher")
    ap.add_argument("--repo", help="Hermes Agent checkout (auto-detected when omitted)")
    ap.add_argument("--set", choices=sorted(SETS), default="source", help="ops set (default: source)")
    ap.add_argument("--verify-only", action="store_true", help="phase A only: check anchors, write nothing")
    ap.add_argument("--dry-run", action="store_true", help="alias of --verify-only")
    ap.add_argument("--json", action="store_true", help="machine-readable report on stdout")
    args = ap.parse_args()

    repo = find_repo(args.repo)
    if repo is None:
        log("ERROR: could not locate a Hermes Agent checkout (pass --repo)")
        return 5

    ops_name, manifest_name = SETS[args.set]
    ops_by_file = json.loads((HERE / ops_name).read_text(encoding="utf-8"))
    # kind: "patch" (search/replace + token), "tokened" (targets present, add
    # the marker only), "create" (brand-new file, write whole + token)
    plan: list[tuple[str, str, list[dict], str]] = []
    report: dict = {
        "repo": str(repo),
        "set": args.set,
        "files": {},
        "phase": "verify-only" if (args.verify_only or args.dry_run) else "apply",
    }

    # ── phase A — classify + verify every anchor, touch nothing ──
    for rel, ops in ops_by_file.items():
        p = repo / rel
        if not p.is_file():
            if is_create(ops):
                report["files"][rel] = {"status": "create"}
                plan.append((rel, "create", ops, ""))
                continue
            report["files"][rel] = {"status": "missing-file"}
            _finish(report, args)
            log(f"ERROR: {rel} not found under {repo}")
            return 5
        text = read_text(p)
        applied = is_fully_applied(text, ops)
        token = has_token(text)
        if applied and token:
            report["files"][rel] = {"status": "already-patched"}
            continue
        if applied and not token:
            # seam already present (e.g. the upstream PR merged upstream): the
            # only delta this tool adds is its marker.
            report["files"][rel] = {"status": "ready-token-only"}
            plan.append((rel, "tokened", [], text))
            continue
        if token and not applied:
            report["files"][rel] = {
                "status": "tampered",
                "detail": "token present but target strings incomplete",
            }
            _finish(report, args)
            log(f"ERROR: {rel} carries the patch token but is not fully patched — refusing to guess")
            return 5
        if is_create(ops):
            # file exists but is neither the base (it never was) nor the seam
            report["files"][rel] = {"status": "anchors-missing", "ops": [0]}
            continue
        miss = missing_anchors(text, ops)
        if miss:
            report["files"][rel] = {"status": "anchors-missing", "ops": miss}
        else:
            report["files"][rel] = {"status": "ready"}
            plan.append((rel, "patch", ops, text))

    pending = [f for f, v in report["files"].items() if v["status"] == "anchors-missing"]
    if pending:
        log("anchors missing — nothing was written (upstream drift? see docs/troubleshooting.md):")
        for f in pending:
            log(f"  - {f}: ops {report['files'][f].get('ops')}")
        _finish(report, args)
        return 2
    if not plan:
        log("nothing to do — desktop seam already patched")
        report["phase"] = "no-op"
        _finish(report, args)
        return 0
    if args.verify_only or args.dry_run:
        log(f"verify-only OK — {len(plan)} file(s) ready: {', '.join(f for f, *_ in plan)}")
        _finish(report, args)
        return 0

    # ── phase B — backup then write ──
    report["phase"] = "apply"
    written: list[dict] = []
    for rel, kind, ops, text in plan:
        p = repo / rel
        if kind == "create":
            bak = None
            new_text = ops[0]["new"]
            if not new_text.endswith("\n"):
                new_text += "\n"
            new_text += token_line(rel) + "\n"
        else:
            bak = backup_path(p)
            shutil.copy2(p, bak)
            new_text = apply_ops(text, ops)
            if not new_text.endswith("\n"):
                new_text += "\n"
            new_text += token_line(rel) + "\n"
        with p.open("w", encoding="utf-8", newline="\n") as fh:
            fh.write(new_text)
        written.append(
            {
                "file": rel,
                "kind": kind,
                "bak": str(bak) if bak else None,
                "sha_before": _sha(text) if text else None,
                "sha_after": _sha(new_text),
            }
        )
        verb = {"patch": "patched", "tokened": "tokened", "create": "created"}[kind]
        log(f"{verb} {rel}" + (f" (backup: {bak.name})" if bak else ""))

    # ── phase C — re-verify everything; rollback on any failure ──
    bad: list[str] = []
    for rel, kind, ops, _ in plan:
        p = repo / rel
        text = read_text(p)
        if not (is_fully_applied(text, ops) and has_token(text)):
            bad.append(rel)
        elif rel.endswith(".py"):
            try:
                ast.parse(text)
            except SyntaxError:
                bad.append(rel)
    if bad:
        log("re-verify FAILED — rolling back the files written in this run")
        unrestored: list[str] = []
        for entry in written:
            p = repo / entry["file"]
            try:
                if entry["bak"]:
                    shutil.copy2(entry["bak"], p)
                    if _sha(read_text(p)) != entry["sha_before"]:
                        unrestored.append(entry["file"])
                else:
                    p.unlink(missing_ok=True)
            except Exception as exc:  # noqa: BLE001 - report, never crash mid-rollback
                unrestored.append(f"{entry['file']} ({exc})")
        report["rollback"] = {"failed_files": bad, "unrestored": unrestored}
        _finish(report, args)
        if unrestored:
            log("ROLLBACK INCOMPLETE — restore these by hand:")
            for u in unrestored:
                log(f"  - {u}")
            return 4
        log("rolled back clean — tree is exactly as before this run")
        return 3

    manifest = {
        "tool": "hermes-composer-modes/desktop-patch",
        "set": args.set,
        "patched_at": _dt.datetime.now().isoformat(timespec="seconds"),
        "files": written,
    }
    (repo / manifest_name).write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    log(f"all good — manifest written to {repo / manifest_name}")
    _finish(report, args)
    return 0


if __name__ == "__main__":
    sys.exit(main())
