# Registers the composer-modes guardian task: re-applies the install after Hermes
# updates (which reset the checkout) and after machine restarts.
#
#   .\ensure-task.ps1           create or update the task (idempotent)
#   .\ensure-task.ps1 -WhatIf   show what it would register
#
# Task: HermesComposerModesEnsure — at logon (+30s) and every 6 hours, running
# install.ps1 -Repair through a hidden VBS launcher (no console flash).
[CmdletBinding(SupportsShouldProcess = $true)]
param(
  [string]$HermesHome
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot
$InstallPs1 = Join-Path $PSScriptRoot 'install.ps1'
$TaskName = 'HermesComposerModesEnsure'

function Fail([int]$code, [string]$msg) { Write-Host "[composer-modes] ERROR: $msg" -ForegroundColor Red; exit $code }
if (-not $IsWindows -and $env:OS -notlike '*Windows*') { Fail 2 'Windows-only release (v1).' }
if (-not (Test-Path $InstallPs1 -PathType Leaf)) { Fail 2 "install.ps1 not found at $InstallPs1" }

function Test-Home([string]$p) { $p -and ((Test-Path (Join-Path $p 'hermes-agent') -PathType Container) -or (Test-Path (Join-Path $p 'config.yaml') -PathType Leaf)) }
$HermesDir = $null
foreach ($c in @($HermesHome, $env:HERMES_HOME, (Join-Path $env:LOCALAPPDATA 'hermes'), (Join-Path $env:USERPROFILE '.hermes'))) {
  if (Test-Home $c) { $HermesDir = $c; break }
}
if (-not $HermesDir) { Fail 2 'could not find the Hermes home; pass -HermesHome.' }

# hidden launcher (no console window flash)
$stateDir = Join-Path $HermesDir 'composer-modes'
New-Item -ItemType Directory -Force -Path $stateDir | Out-Null
$vbs = Join-Path $stateDir 'launch-ensure.vbs'
$vbsContent = @"
' composer-modes ensure launcher (hidden console) - generated by ensure-task.ps1
Set sh = CreateObject("WScript.Shell")
sh.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File ""$InstallPs1"" -Repair", 0, False
"@

if ($PSCmdlet.ShouldProcess($TaskName, 'register scheduled task')) {
  Set-Content -Path $vbs -Value $vbsContent -Encoding ASCII

  $action = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument "//B //Nologo `"$vbs`""
  $t1 = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
  $t1.Delay = 'PT30S'
  $t2 = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) `
    -RepetitionInterval (New-TimeSpan -Hours 6) -RepetitionDuration ([TimeSpan]::FromDays(3650))
  $principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited
  $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -MultipleInstances IgnoreNew

  if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Set-ScheduledTask -TaskName $TaskName -Action $action -Trigger @($t1, $t2) -Principal $principal -Settings $settings | Out-Null
    Write-Host "[composer-modes] task updated: $TaskName"
  } else {
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger @($t1, $t2) -Principal $principal -Settings $settings | Out-Null
    Write-Host "[composer-modes] task registered: $TaskName (logon +30s, then every 6h)"
  }
  Write-Host "[composer-modes] log: $(Join-Path $stateDir 'install.log')"
} else {
  Write-Host "[composer-modes] would register task '$TaskName' -> wscript $vbs (install.ps1 -Repair; logon +30s, every 6h)"
}
exit 0
